#include "../Global.h"

typedef enum RPGKey{
    RPG_KEY_UNKNOWN       = -1,

    RPG_KEY_SPACE         = 32,
    RPG_KEY_APOSTROPHE    = 39,
    RPG_KEY_COMMA         = 44,
    RPG_KEY_MINUS         = 45,
    RPG_KEY_PERIOD        = 46,
    RPG_KEY_SLASH         = 47,
    RPG_KEY_0             = 48,
    RPG_KEY_1             = 49,
    RPG_KEY_2             = 50,
    RPG_KEY_3             = 51,
    RPG_KEY_4             = 52,
    RPG_KEY_5             = 53,
    RPG_KEY_6             = 54,
    RPG_KEY_7             = 55,
    RPG_KEY_8             = 56,
    RPG_KEY_9             = 57,
    RPG_KEY_SEMICOLON     = 59,
    RPG_KEY_EQUAL         = 61,
    RPG_KEY_A             = 65,
    RPG_KEY_B             = 66,
    RPG_KEY_C             = 67,
    RPG_KEY_D             = 68,
    RPG_KEY_E             = 69,
    RPG_KEY_F             = 70,
    RPG_KEY_G             = 71,
    RPG_KEY_H             = 72,
    RPG_KEY_I             = 73,
    RPG_KEY_J             = 74,
    RPG_KEY_K             = 75,
    RPG_KEY_L             = 76,
    RPG_KEY_M             = 77,
    RPG_KEY_N             = 78,
    RPG_KEY_O             = 79,
    RPG_KEY_P             = 80,
    RPG_KEY_Q             = 81,
    RPG_KEY_R             = 82,
    RPG_KEY_S             = 83,
    RPG_KEY_T             = 84,
    RPG_KEY_U             = 85,
    RPG_KEY_V             = 86,
    RPG_KEY_W             = 87,
    RPG_KEY_X             = 88,
    RPG_KEY_Y             = 89,
    RPG_KEY_Z             = 90,
    RPG_KEY_LEFT_BRACKET  = 91,
    RPG_KEY_BACKSLASH     = 92,
    RPG_KEY_RIGHT_BRACKET = 93,
    RPG_KEY_GRAVE_ACCENT  = 96,
    RPG_KEY_WORLD_1       = 161,
    RPG_KEY_WORLD_2       = 162,

    RPG_KEY_ESCAPE        = 256,
    RPG_KEY_ENTER         = 257,
    RPG_KEY_TAB           = 258,
    RPG_KEY_BACKSPACE     = 259,
    RPG_KEY_INSERT        = 260,
    RPG_KEY_DELETE        = 261,
    RPG_KEY_RIGHT         = 262,
    RPG_KEY_LEFT          = 263,
    RPG_KEY_DOWN          = 264,
    RPG_KEY_UP            = 265,
    RPG_KEY_PAGE_UP       = 266,
    RPG_KEY_PAGE_DOWN     = 267,
    RPG_KEY_HOME          = 268,
    RPG_KEY_END           = 269,
    RPG_KEY_CAPS_LOCK     = 280,
    RPG_KEY_SCROLL_LOCK   = 281,
    RPG_KEY_NUM_LOCK      = 282,
    RPG_KEY_PRINT_SCREEN  = 283,
    RPG_KEY_PAUSE         = 284,
    RPG_KEY_F1            = 290,
    RPG_KEY_F2            = 291,
    RPG_KEY_F3            = 292,
    RPG_KEY_F4            = 293,
    RPG_KEY_F5            = 294,
    RPG_KEY_F6            = 295,
    RPG_KEY_F7            = 296,
    RPG_KEY_F8            = 297,
    RPG_KEY_F9            = 298,
    RPG_KEY_F10           = 299,
    RPG_KEY_F11           = 300,
    RPG_KEY_F12           = 301,
    RPG_KEY_F13           = 302,
    RPG_KEY_F14           = 303,
    RPG_KEY_F15           = 304,
    RPG_KEY_F16           = 305,
    RPG_KEY_F17           = 306,
    RPG_KEY_F18           = 307,
    RPG_KEY_F19           = 308,
    RPG_KEY_F20           = 309,
    RPG_KEY_F21           = 310,
    RPG_KEY_F22           = 311,
    RPG_KEY_F23           = 312,
    RPG_KEY_F24           = 313,
    RPG_KEY_F25           = 314,
    RPG_KEY_KP_0          = 320,
    RPG_KEY_KP_1          = 321,
    RPG_KEY_KP_2          = 322,
    RPG_KEY_KP_3          = 323,
    RPG_KEY_KP_4          = 324,
    RPG_KEY_KP_5          = 325,
    RPG_KEY_KP_6          = 326,
    RPG_KEY_KP_7          = 327,
    RPG_KEY_KP_8          = 328,
    RPG_KEY_KP_9          = 329,
    RPG_KEY_KP_DECIMAL    = 330,
    RPG_KEY_KP_DIVIDE     = 331,
    RPG_KEY_KP_MULTIPLY   = 332,
    RPG_KEY_KP_SUBTRACT   = 333,
    RPG_KEY_KP_ADD        = 334,
    RPG_KEY_KP_ENTER      = 335,
    RPG_KEY_KP_EQUAL      = 336,
    RPG_KEY_LEFT_SHIFT    = 340,
    RPG_KEY_LEFT_CONTROL  = 341,
    RPG_KEY_LEFT_ALT      = 342,
    RPG_KEY_LEFT_SUPER    = 343,
    RPG_KEY_RIGHT_SHIFT   = 344,
    RPG_KEY_RIGHT_CONTROL = 345,
    RPG_KEY_RIGHT_ALT     = 346,
    RPG_KEY_RIGHT_SUPER   = 347,
    RPG_KEY_MENU          = 348
}RPGKey;

#define RPGKeyLast KB_KEY_LAST

typedef enum RPGMouseButton{
    RPG_MOUSE_0 = MOUSE_BTN_0, // No mouse button
    RPG_MOUSE_1 = MOUSE_BTN_1,
    RPG_MOUSE_2 = MOUSE_BTN_2,
    RPG_MOUSE_3 = MOUSE_BTN_3,
    RPG_MOUSE_4= MOUSE_BTN_4,
    RPG_MOUSE_5= MOUSE_BTN_5,
    RPG_MOUSE_6= MOUSE_BTN_6,
    RPG_MOUSE_7= MOUSE_BTN_7,
}RPGMouseButton;

#define RPGMouseLeft MOUSE_LEFT
#define RPGMouseRight MOUSE_RIGHT
#define RPGMouseMiddle MOUSE_MIDDLE



typedef enum RPGKeyMod{
    RPG_MOD_SHIFT        = KB_MOD_SHIFT,
    RPG_MOD_CONTROL      = KB_MOD_CONTROL,
    RPG_MOD_ALT          = KB_MOD_ALT,
    RPG_MOD_SUPER        = KB_MOD_SUPER,
    RPG_MOD_CAPS_LOCK    = KB_MOD_CAPS_LOCK,
    RPG_MOD_NUM_LOCK     = KB_MOD_NUM_LOCK
}RPGKeyMod;